services:
  - type: web
    name: nano-url
    env: go
    buildCommand: go build -o main .
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: DB_URL
        fromDatabase:
          name: nano-db
          property: connectionString
      - key: RUN_MIGRATIONS
        value: true

databases:
  - name: nano-db
    databaseName: nano
    user: nano_user
