// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	Expiry    time.Time
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Token     string
	Expiry    time.Time
	CreatedAt sql.NullTime
}

type Url struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Url         string
	ShortUrl    string
	TotalClicks sql.NullInt32
	DailyClicks sql.NullInt32
	LastClicked sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PfpUrl         string
}

type UserAnalytic struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	TotalUrls        int32
	TotalTotalClicks int32
	AvgDailyClicks   float64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}
